### ISSUE TITLE
High Yield Tags: "Number of Tags" function not working on Anki version 2.1.44

### ISSUE THREAD

**Issue by ayobamiii** [AnKing-Memberships/high-yield-tags#11]
Below is the error message I receive when trying to use the "Number of Tags" function 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-13 16:32:15

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ayoba\AppData\Roaming\Anki2\addons21\1918380616\__init__.py", line 132, in <lambda>
    a.triggered.connect(lambda: showTagsInfo(browser, browser.selectedCards()))
  File "C:\Users\ayoba\AppData\Roaming\Anki2\addons21\1918380616\__init__.py", line 36, in showTagsInfo
    info = tagStats(cids, highlights, highlights_percent)
  File "C:\Users\ayoba\AppData\Roaming\Anki2\addons21\1918380616\__init__.py", line 96, in tagStats
    nbCardWithThisTag = len(mw.col.findCards(search))
  File "anki\collection.py", line 478, in find_cards
  File "anki\_backend\generated.py", line 80, in search_cards
  File "anki\_backend\__init__.py", line 106, in _run_command
anki.errors.InvalidInput: Invalid search: ⁨the escape sequence `⁨\#⁩` is not defined. If you want to search for a literal backslash `\`, prepend another one: `\\`.⁩

**Comment by italianmafia** [comment]
Same error is happening to with both functions
